name: Main Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v3

      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: check  node and go
        run: |
          node --version
          go version
